---
# Default values for iks_helm_deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environmentName: helm-default
replicaCount: 1
image: webapp
imagePullPolicy: Always
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
    ephemeralStorage: "1Gi"
service:
  type: NodePort
ingress:
  enabled: false
  host: cluster-ingress-subdomain
  #secret: <secret for TLS>
secret:
  dockerconfigjson: 
cluster:
  type: iks