# Documentation on available configuration
# https://cloud.ibm.com/docs/devsecops?topic=devsecops-cd-devsecops-apps-byoa
# https://cloud.ibm.com/docs/devsecops?topic=devsecops-custom-scripts

version: '2'

tasks:

  code-checks:
    include:
      - dind
    steps:
      - name: checks-setup
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash
          if [[ "$PIPELINE_DEBUG" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi
          if [[ "$(get_env pipeline_namespace)" == *"pr"* ||  "$(get_env pipeline_namespace)" == *"ci"* ]]; then
            source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/code_setup.sh

            # ensure we're located in the source app repo
            cd "$WORKSPACE/$(load_repo app-repo path)"

            # update the dependency in the source app
            npm ci
          fi
      - name: detect-secrets
        include:
          - docker-socket

      - name: compliance-checks
        include:
          - docker-socket

      - name: static-scan
        include:
          - docker-socket
  code-build:
    include:
      - dind
    steps:
      - name: setup
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash
          if [[ "$PIPELINE_DEBUG" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi
          if [[ "$(get_env pipeline_namespace)" == *"pr"* ||  "$(get_env pipeline_namespace)" == *"ci"* ]]; then
            source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/code_setup.sh

            # ensure we're located in the source app repo
            cd "$WORKSPACE/$(load_repo app-repo path)"

            # update the dependency in the source app
            npm ci
          fi
      - name: unit-test
        onError: continue
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash
          if [[ "$PIPELINE_DEBUG" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi
          # ensure we're located in the source app repo
          cd "$WORKSPACE/$(load_repo app-repo path)"
          source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/run_test.sh
          run_unit_test
      - name: build-artifact
        include:
          - docker-socket
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash

          if [[ "$PIPELINE_DEBUG" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi

          # ensure we build the app repo Dockerfile
          cd "$WORKSPACE/$(load_repo app-repo path)"

          source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/build_setup.sh
          source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/build.sh
      - name: sign-artifact
        when: 'false'

  deploy-checks:
    include:
      - dind
    steps:
      - name: deploy
        image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.59
        script: |
          #!/usr/bin/env bash

          if [[ "$PIPELINE_DEBUG" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi

          source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/run_test.sh
          source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/deploy_setup.sh
          if [[ $(get_env deployment-type "deployment") == "helm" ]]; then
            source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/deploy_helm.sh
            save_deployment_artifact iks_helm_deployment/Chart.yaml IKS helm
            save_deployment_artifact iks_helm_deployment/values.yaml IKS dev-config
            save_deployment_artifact os_helm_deployment/values.yaml OPENSHIFT dev-config
            save_deployment_artifact os_helm_deployment/Chart.yaml OPENSHIFT helm
          else
            source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/deploy.sh
            save_deployment_artifact deployment_iks.yml IKS deployment
            save_deployment_artifact deployment_os.yml OPENSHIFT deployment
          fi
      - name: dynamic-scan
        include:
          - docker-socket
        onError: continue
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash
          if [[ "$PIPELINE_DEBUG" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi
          if [ -z "$(get_env opt-in-dynamic-scan "")" ]; then
            echo "If you want to enable this stage, add 'opt-in-dynamic-scan' parameter to your pipeline with any value. Also, please add 'opt-in-dynamic-api-scan' to your pipeline with any value to have api scans running, and 'opt-in-dynamic-ui-scan' with any value to have ui scans running" >&2
          else
            if [[ "$(get_env pipeline_namespace)" == *"cc"* ]]; then
              app_url=$(get_env app-url "")
              if [[ -z "${app_url}" ]]; then
                echo "Please provide the app-url as the running application url. Recommended to use stage/test environment to run the Dynamic scan." >&2
                exit 1
              fi
              source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/zap/zap-cc-config
            fi
            source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/zap/trigger-async-zap
          fi

      - name: acceptance-test
        onError: continue
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
        script: |
          #!/usr/bin/env bash

          export APP_URL=$(get_env app-url)
          source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/run_test.sh    
          run_acceptance_test


  deploy-release:
    steps:
      - name: run-stage
        onError: continue
        image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.59
        script: |
          #!/usr/bin/env bash
          if [[ "$PIPELINE_DEBUG" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi
          source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/run_test.sh
          save_deployment_artifact iks_helm_deployment/pre-prod-values.yaml IKS pre-prod-config
          save_deployment_artifact iks_helm_deployment/prod-values.yaml IKS prod-config
          save_deployment_artifact os_helm_deployment/pre-prod-values.yaml OPENSHIFT pre-prod-config
          save_deployment_artifact os_helm_deployment/prod-values.yaml OPENSHIFT prod-config
          source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/release.sh

  async-dast-scan:
    include:
      - dind
    steps:
      - name: run-stage
        include:
          - docker-socket
        image: icr.io/continuous-delivery/pipeline/pipeline-base-image:3.46
      - name: owasp-zap
        script: |
          #!/usr/bin/env bash

          source $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/scripts/zap/trigger_zap_scans
