kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.networkPolicy }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - ports:
    - port: {{ .Values.targetPort }}
