apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeportService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ .Values.nodeportService.labels | toYaml }}
spec:
  type: {{ .Values.nodeportService.type }}
  ports:
    - port: {{ .Values.targetPort }}
  selector:
    {{ .Values.nodeportService.labels | toYaml }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ .Values.labels | toYaml }}
spec:
  type: {{ .Values.clusterService.type }}
  ports:
    - port: {{ .Values.clusterService.port }}
      targetPort: {{ .Values.targetPort }}
  selector:
    {{ .Values.labels | toYaml }}