apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{  .Chart.Name }}"
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: "{{  .Chart.Name }}"
      chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{  .Chart.Name }}"
        chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    spec:
      imagePullSecrets:
      - name: "image-registry-pull-secret"
      automountServiceAccountToken: false
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
          - name: ENVIRONMENT_NAME
            value: "{{ .Values.environmentName }}"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
              ephemeral-storage: "{{ .Values.resources.limits.ephemeralStorage }}"
