apiVersion: v1
kind: Secret
metadata:
  name: "image-registry-pull-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{  .Chart.Name }}"
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
data:
  .dockerconfigjson: {{ .Values.secret.dockerconfigjson | default "eyJhdXRocyI6e319" }}
type: kubernetes.io/dockerconfigjson
