apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{  .Chart.Name }}"
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      {{- if or (contains "LoadBalancer" .Values.service.type) (contains "ClusterIP" .Values.service.type)}}
      port: 80
      {{- else}}
      port: 8080
      {{- end}}
      targetPort: 8080
  selector:
    app: "{{  .Chart.Name }}"
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
