name: Build and SonarQube Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your Node.js code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure a full clone for accurate analysis

      # Step 2: Run SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Step 3: Fetch the SonarQube analysis status as JSON (if available)
      - name: Generate JSON Report from SonarCloud
        run: |
          curl -u $SONAR_TOKEN: \
            -o sonar-report.json \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY"
        
      # Step 4: Debug API Response
      - name: Debug API Response
        run: |
          cat sonar-report.json

      # Step 5: Upload JSON report to GitHub Artifacts
      - name: Upload JSON Report to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sonarcloud-json-report
          path: sonar-report.json
