name: Build and SonarQube Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Install Dependencies
        run: |
          npm install

      - name: Run Tests and Generate Coverage Report
        run: |
          npm test -- --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
      - name: Generate Sonar Report
        run: |
          curl -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/issues/search?componentKeys=${{ secrets.SONAR_PROJECT_KEY }}&resolved=false&ps=500" -o sonar_report.json

      - name: Upload Sonar Report to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sonarcloud-report
          path: sonar_report.json

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: sonar-coverage.json
